package com.fanlm.entity;

public class Action {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.ID
     *
     * @mbg.generated Mon Dec 07 23:24:13 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.URL
     *
     * @mbg.generated Mon Dec 07 23:24:13 CST 2020
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action.ID
     *
     * @return the value of action.ID
     *
     * @mbg.generated Mon Dec 07 23:24:13 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action.ID
     *
     * @param id the value for action.ID
     *
     * @mbg.generated Mon Dec 07 23:24:13 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action.URL
     *
     * @return the value of action.URL
     *
     * @mbg.generated Mon Dec 07 23:24:13 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action.URL
     *
     * @param url the value for action.URL
     *
     * @mbg.generated Mon Dec 07 23:24:13 CST 2020
     */
    public void setUrl(String url) {
        this.url = url;
    }
}