package com.fanlm.entity;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.ID
     *
     * @mbg.generated Mon Dec 07 23:24:13 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.NAME
     *
     * @mbg.generated Mon Dec 07 23:24:13 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.ID
     *
     * @return the value of role.ID
     *
     * @mbg.generated Mon Dec 07 23:24:13 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.ID
     *
     * @param id the value for role.ID
     *
     * @mbg.generated Mon Dec 07 23:24:13 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.NAME
     *
     * @return the value of role.NAME
     *
     * @mbg.generated Mon Dec 07 23:24:13 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.NAME
     *
     * @param name the value for role.NAME
     *
     * @mbg.generated Mon Dec 07 23:24:13 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }
}