package com.fanlm.entity;

public class RoleAction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_action.ID
     *
     * @mbg.generated Mon Dec 07 23:24:13 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_action.ACTION_ID
     *
     * @mbg.generated Mon Dec 07 23:24:13 CST 2020
     */
    private String actionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_action.ROLE_ID
     *
     * @mbg.generated Mon Dec 07 23:24:13 CST 2020
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_action.ID
     *
     * @return the value of role_action.ID
     *
     * @mbg.generated Mon Dec 07 23:24:13 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_action.ID
     *
     * @param id the value for role_action.ID
     *
     * @mbg.generated Mon Dec 07 23:24:13 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_action.ACTION_ID
     *
     * @return the value of role_action.ACTION_ID
     *
     * @mbg.generated Mon Dec 07 23:24:13 CST 2020
     */
    public String getActionId() {
        return actionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_action.ACTION_ID
     *
     * @param actionId the value for role_action.ACTION_ID
     *
     * @mbg.generated Mon Dec 07 23:24:13 CST 2020
     */
    public void setActionId(String actionId) {
        this.actionId = actionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_action.ROLE_ID
     *
     * @return the value of role_action.ROLE_ID
     *
     * @mbg.generated Mon Dec 07 23:24:13 CST 2020
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_action.ROLE_ID
     *
     * @param roleId the value for role_action.ROLE_ID
     *
     * @mbg.generated Mon Dec 07 23:24:13 CST 2020
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
}